import {gaussian,blur,sobel,fixture,sample} from './model.mjs';
const $=id=>document.getElementById(id);
const ink='#34363d',muted='#858994',purple='#6465c6',orange='#c88945';
const values=[15,15,15,15,15,15,15,15,40,40,15,15,15,15,15,40,220,40,15,15,15,15,40,220,220,220,40,15,15,15,15,15,15,15,15];
const row=[20,20,20,60,220,220,60,20,20],step=[30,30,30,30,220,220,220,220,220];
const diagrams=new Map(),animations=new Map();
let inversion=0,inverted=false,invertFrame;
const fmt=n=>Number(n.toFixed(2)).toString();
function setup(id,draw){const canvas=$(id);const render=()=>{const w=canvas.clientWidth,h=canvas.clientHeight,dpr=devicePixelRatio||1;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);draw(ctx,w,h);};diagrams.set(id,render);new ResizeObserver(render).observe(canvas);render();}
function label(c,text,x,y,color=muted,size=14){c.fillStyle=color;c.font=`${size}px APL, monospace`;c.textAlign='center';c.textBaseline='middle';c.fillText(text,x,y);}
function tile(c,v,x,y,size,number=false,gap=2){const gray=Math.round(Math.max(0,Math.min(255,v)));c.fillStyle=`rgb(${gray},${gray},${gray})`;c.fillRect(x+gap/2,y+gap/2,size-gap,size-gap);if(number)label(c,Math.round(v),x+size/2,y+size/2,gray>125?ink:'#fff',Math.max(12,Math.min(16,size*.29)));}
function drawGrid(c,a,h,w,x,y,size,{numbers=false,gap=2,gain=1}={}){a.forEach((v,i)=>tile(c,v*gain,x+i%w*size,y+Math.floor(i/w)*size,size,numbers,gap));}
function slider(id,canvas){$(id).addEventListener('input',()=>{pause(id);diagrams.get(canvas)();});}
setup('pixels',(c,w,h)=>{const t=+$('reveal').value,size=Math.min((w-24)/7,46),x=(w-7*size)/2,y=(h-5*size)/2;drawGrid(c,values,5,7,x,y,size,{gap:1+8*t});if(t>0){c.globalAlpha=t;values.forEach((v,i)=>label(c,v,x+(i%7+.5)*size,y+(Math.floor(i/7)+.5)*size,v>125?ink:'#fff',Math.max(12,size*.31)));c.globalAlpha=1;}});slider('reveal','pixels');
setup('invert',(c,w,h)=>{const size=Math.min((w-24)/7,43),x=(w-7*size)/2,y=(h-5*size)/2;const a=values.map(v=>v+(255-2*v)*inversion);drawGrid(c,a,5,7,x,y,size,{numbers:true,gap:4});});
$('invert-toggle').addEventListener('click',()=>{inverted=!inverted;$('invert-toggle').setAttribute('aria-pressed',String(inverted));$('invert-toggle').textContent=inverted?'Restore the picture':'Invert the picture';cancelAnimationFrame(invertFrame);const start=inversion,end=inverted?1:0,t0=performance.now();function tick(now){const t=matchMedia('(prefers-reduced-motion: reduce)').matches?1:Math.min(1,(now-t0)/650);inversion=start+(end-start)*t;diagrams.get('invert')();if(t<1)invertFrame=requestAnimationFrame(tick);}invertFrame=requestAnimationFrame(tick);});
setup('transpose',(c,w,h)=>{const t=+$('turn').value,size=Math.min((w-36)/5,(h-60)/5,49);for(let i=0;i<15;i++){const y=Math.floor(i/5),x=i%5,fromX=(w-5*size)/2+x*size,fromY=(h-3*size)/2+y*size,toX=(w-3*size)/2+y*size,toY=(h-5*size)/2+x*size;const xx=fromX+(toX-fromX)*t,yy=fromY+(toY-fromY)*t;c.fillStyle=`hsl(${235+x*7},${30+y*9}%,${77-y*7}%)`;c.fillRect(xx+2,yy+2,size-4,size-4);label(c,i+1,xx+size/2,yy+size/2,ink,16);}label(c,t<.01?'3 rows, 5 columns':t>.99?'5 rows, 3 columns':'Every value keeps its identity',w/2,h-14);});slider('turn','transpose');
function neighborhood(c,w,h,isEdge){const id=isEdge?'edge-position':'position',a=isEdge?step:row,weights=isEdge?[-1,0,1]:[.25,.5,.25],p=+$ (id).value,i=Math.round(p),size=Math.min((w-20)/9,48),left=(w-9*size)/2,top=45;label(c,'input',w/2,20);a.forEach((v,k)=>tile(c,v,left+k*size,top,size,true,3));c.strokeStyle=purple;c.lineWidth=2;c.strokeRect(left+(p-1)*size+1,top-5,size*3-2,size+10);const neighbors=weights.map((_,k)=>sample(a,1,9,0,i+k-1,'clamp'));const products=weights.map((v,k)=>v*neighbors[k]);const middle=w/2,spacing=Math.min(130,(w-20)/3);for(let k=0;k<3;k++){const xx=middle+(k-1)*spacing;label(c,`${fmt(weights[k])} × ${neighbors[k]}`,xx,top+size+54,k===1?purple:muted,w<430?14:16);label(c,fmt(products[k]),xx,top+size+87,ink,17);if(k<2)label(c,'+',xx+spacing/2,top+size+87,muted,18);}const sum=products.reduce((a,b)=>a+b,0);label(c,`= ${fmt(sum)}`,middle,top+size+123,purple,22);const out=a.map((_,k)=>weights.reduce((total,v,j)=>total+v*sample(a,1,9,0,k+j-1,'clamp'),0));const base=h-25;out.forEach((v,k)=>{const height=(isEdge?v/220:v/255)*40;c.fillStyle=k===i?purple:'#d6d6e9';c.fillRect(left+k*size+3,base-height,size-6,Math.max(1,height));});label(c,isEdge?'difference':'output brightness',w/2,base+15,muted,12);$(isEdge?'edge-caption':'window-caption').textContent=isEdge?`At position ${i+1}: ${neighbors[2]} − ${neighbors[0]} = ${sum}.`:`At position ${i+1}, the weighted average is ${fmt(sum)}.`;}
setup('window',(c,w,h)=>neighborhood(c,w,h,false));slider('position','window');setup('edge',(c,w,h)=>neighborhood(c,w,h,true));slider('edge-position','edge');
setup('gaussian',(c,w,h)=>{const sigma=+$('spread').value,k=gaussian(4,sigma),size=Math.min((w-28)/9,55),left=(w-9*size)/2,base=h-60,scale=h-110;k.forEach((v,i)=>{const x=left+i*size;c.fillStyle=i===4?purple:'#b8b8e0';c.fillRect(x+5,base-v*scale,size-10,v*scale);label(c,fmt(v),x+size/2,base-v*scale-15,i===4?purple:muted,w<430?12:14);label(c,i-4,x+size/2,base+20,muted,14);});label(c,'pixel offset',w/2,h-10);$('spread-value').textContent=sigma.toFixed(2);});slider('spread','gaussian');
const impulse=Array(81).fill(0);impulse[40]=255;const blurred=blur(impulse,9,9,4,1,'clamp');
setup('passes',(c,w,h)=>{const t=+$('pass').value,first=t<=1,amount=first?t:t-1,from=first?impulse:blurred.horizontal,to=first?blurred.horizontal:blurred.output,a=from.map((v,i)=>v+(to[i]-v)*amount),size=Math.min((w-30)/9,(h-45)/9,32),left=(w-9*size)/2,top=12;drawGrid(c,a,9,9,left,top,size,{gap:2,gain:3});label(c,t<.01?'one bright pixel':first?'spreading across a row':'spreading down the columns',w/2,h-13);$('passes-caption').textContent=t<1?'First, brightness spreads across the row.':'Then each column is blurred. The line becomes a spot.';});slider('pass','passes');
const source=fixture('shape',0,84,108),edges=sobel(source.pixels,84,108,'clamp').magnitude,edgeMax=Math.max(...edges);
setup('edge-image',(c,w,h)=>{const t=+$('edge-reveal').value,width=Math.min(w-36,430),height=width*84/108,top=(h-height)/2,left=(w-width)/2,s=width/108;source.pixels.forEach((v,i)=>{const x=i%108,y=Math.floor(i/108);const val=x/108<t?edges[i]/edgeMax*255:v;const b=Math.round(val);c.fillStyle=`rgb(${b},${b},${b})`;c.fillRect(left+x*s,top+y*s,s+.5,s+.5);});c.strokeStyle=purple;c.lineWidth=2;c.beginPath();c.moveTo(left+t*width,top-8);c.lineTo(left+t*width,top+height+8);c.stroke();});slider('edge-reveal','edge-image');
const playable={position:'window',pass:'passes','edge-position':'edge'};
function pause(id){const a=animations.get(id);if(a)cancelAnimationFrame(a.frame);animations.delete(id);const b=document.querySelector(`[data-play="${id}"]`);if(b){b.textContent='Play';b.setAttribute('aria-label',b.getAttribute('aria-label').replace(/^Pause /,'Play '));b.setAttribute('aria-pressed','false');}const caption=id==='position'?'window-caption':id==='edge-position'?'edge-caption':null;if(caption)$(caption).setAttribute('aria-live','polite');}
for(const button of document.querySelectorAll('[data-play]')){button.addEventListener('click',()=>{const id=button.dataset.play;if(animations.has(id)){pause(id);return;}const control=$(id),max=+control.max;let last=performance.now();const animation={frame:0,position:+control.value>=max?0:+control.value};animations.set(id,animation);button.textContent='Pause';button.setAttribute('aria-label',button.getAttribute('aria-label').replace(/^Play /,'Pause '));button.setAttribute('aria-pressed','true');const caption=id==='position'?'window-caption':id==='edge-position'?'edge-caption':null;if(caption)$(caption).setAttribute('aria-live','off');if(+control.value>=max)control.value=0;function tick(now){animation.position=Math.min(max,animation.position+(now-last)*max*Number($('playback-speed').value)/10000);control.value=animation.position;last=now;diagrams.get(playable[id])();if(+control.value>=max){pause(id);return;}animation.frame=requestAnimationFrame(tick);}animation.frame=requestAnimationFrame(tick);});}
function pauseAll(){for(const id of [...animations.keys()])pause(id);cancelAnimationFrame(invertFrame);}
$('pause-all').addEventListener('click',pauseAll);document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseAll();});
const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(!entry.isIntersecting){for(const [id,canvas] of Object.entries(playable))if(canvas===entry.target.id)pause(id);if(entry.target.id==='invert')cancelAnimationFrame(invertFrame);}},{threshold:0});for(const id of [...Object.values(playable),'invert'])observer.observe($(id));
document.fonts.ready.then(()=>diagrams.forEach(render=>render()));

for(const id of ['position','edge-position'])$(id).addEventListener('keydown',event=>{if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();const control=$(id);control.value=Math.max(0,Math.min(8,Math.round(+control.value)+(event.key==='ArrowRight'?1:-1)));control.dispatchEvent(new Event('input'));}});
let readingStep=0;
$('read-step').addEventListener('click',()=>{
  readingStep=(readingStep+1)%3;
  const stages=[
    ['+/0.25 0.5 0.25×20 60 220','It multiplies three pairs of numbers, then adds the results.','Show the multiplication'],
    ['+/5 30 55','0.25 × 20 = 5, 0.5 × 60 = 30, and 0.25 × 220 = 55.','Add the three results'],
    ['90','The slash makes + add along the list: 5 + 30 + 55 = 90.','Read it again']
  ];
  const [expression,note,button]=stages[readingStep];
  $('reading-expression').textContent=expression;$('reading-note').textContent=note;$('read-step').textContent=button;
});
